version: '3'

services:
  nette_apache:
    image: nette_master:latest
    container_name: nette_apache
    networks:
      - nginxdb_proxy
      - graylog_default
    volumes:
      - .:/var/www/html
    command: /var/www/html/init-master.sh
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=nette.local
      - TZ=Europe/Vienna

networks:
  graylog_default:
    external: true
  nginxdb_proxy:
    external: true
